# urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeApiView.as_view(), name='home'),
    path('login', views.LoginApiView.as_view(), name='login'),
    path('register', views.RegisterApiView.as_view(), name='register'),
    path('create-account', views.CreateAccountApiView.as_view(), name='create_account'),
    path('logout', views.LogoutApiView.as_view(), name='logout'),
    path('campus-connect', views.CampusConnectApiView.as_view(), name='campus_connect'),
    path('profile', views.ProfileApiView.as_view(), name='profile'),
    path('show-profile', views.SeeAnotherProfileApiView.as_view(), name='show_profile'),
    path('edit-profile', views.EditProfileApiView.as_view(), name='edit_profile'),
    path('edit-account', views.EditAccountApiView.as_view(), name='edit_account'),
    path('add', views.AddApiView.as_view(), name='add'),
    path('add-post', views.AddPostApiView.as_view(), name='add_post'),
    path('add-entry', views.AddEntryApiView.as_view(), name='add_entry'),
    path('add-donation', views.AddDonationApiView.as_view(), name='add_donation'),
    path('add-borrow-ad', views.AddBorrowAdApiView.as_view(), name='add_borrow_ad'),
    path('add-comment', views.AddCommentApiView.as_view(), name='add_comment'),
    path('market', views.MarketApiView.as_view(), name='market'),
    path('forum', views.ForumApiView.as_view(), name='forum'),
    path('chats', views.ChatsApiView.as_view(), name='chats'),
    path('chat-room', views.ChatRoomApiView.as_view(), name='chat_room'),
    path('send-message', views.SendMessageApiView.as_view(), name='send_message'),
    path('show-post', views.ShowPostApiView.as_view(), name='show_post'),
    path('delete-post', views.DeletePostApiView.as_view(), name='delete_post'),
    path('edit-post', views.EditPostApiView.as_view(), name='edit_post'),
    path('edit-post-contents', views.EditPostContentsApiView.as_view(), name='edit_post_contents'),
    path('sold-post', views.SoldPostApiView.as_view(), name='sold_post'),
    path('report', views.ReportApiView.as_view(), name='report'),
    path('search/', views.SearchResultsApiView.as_view(), name='search_results'),
    path('profile/change-password', views.ChangePasswordApiView.as_view(), name='change_password'),
    path('api/categories/<int:type>/', views.get_categories, name='get_categories'),
    path('api/subcategories/<int:category_id>/', views.get_subcategories, name='get_subcategories'),

    path('get_messages_by_chat_id/<int:chat_id>/', views.get_messages_by_chat_id, name='get_messages_by_chat_id'),
    path('get_last_refresh_timestamp/<int:chat_id>/', views.get_last_refresh_timestamp, name='get_last_refresh_timestamp'),

    path('favorite_post/<int:post_id>/', views.favorite_post, name='favorite_post'),
    path('unfavorite_post/<int:post_id>/', views.unfavorite_post, name='unfavorite_post'),
    path('like_entry/<int:entry_id>/', views.like_entry, name='like_entry'),
    path('unlike_entry/<int:entry_id>/', views.unlike_entry, name='unlike_entry'),
    path('error_view', views.error_view, name='error_view'),
    path('activate/<uidb64>/<token>/', views.activate_account, name='activate'),
]
