# Generated by Django 5.0 on 2023-12-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_connect', '0002_entry_likes_number_post_favorites_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='likes_number',
        ),
        migrations.RemoveField(
            model_name='post',
            name='favorites_number',
        ),
    ]
