# Generated by Django 5.0 on 2023-12-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_connect', '0003_remove_entry_likes_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='likes_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='favorites_number',
            field=models.IntegerField(default=0),
        ),
    ]
