# Generated by Django 5.0 on 2023-12-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_connect', '0005_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default='https://firebasestorage.googleapis.com/v0/b/facid-6fd44.appspot.com/o/profilePhotos%2FUntitled_Artwork.png?alt=media&token', max_length=1000),
        ),
    ]
